base_page/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register_view, dashboard, login_view, logout_view

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("register/", register_view, name="register_view"),
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout"),
 
]

loginRegAuth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('base_page.urls', 'base_page'), namespace='base_page')),
] + static(settings.STATIC_URL)

base_page/models.py
from django.db import models

# Create your models here.

base_page/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

base_page/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth import login, logout
from base_page.forms import RegisterUserForm
# Create your views here.

@login_required(login_url='/login/')
def dashboard(request):
    return render(request, "dashboard.html", {})

def register_view(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST or None)
        if form.is_valid():
            # form.save()
            login(request, form.save())
            # return redirect("base_page:login_view")
        
    else:
        form = RegisterUserForm()
    if request.user.is_authenticated:
        return redirect("base_page:dashboard")
    else:
        return render(request, "registration/register.html", {"form": form})
    
def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST) 
        if form.is_valid():
            login(request, form.get_user())
            return redirect("base_page:dashboard")
    else: 
        form = AuthenticationForm() 

    if request.user.is_authenticated:
        return redirect("base_page:dashboard")
    
    return render(request, "registration/login.html", {"form": form})

@login_required(login_url='/login/')
def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("base_page:login_view")
    
    return redirect("base_page:dashboard")

base_page/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Sign up / Login Form</title>
  <!-- <link rel="stylesheet" href="./style.css"> -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<link rel="stylesheet" type="text/css" href="slide navbar style.css">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    {% block content %}{% endblock content %}
	<!-- <div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="txt" placeholder="User name" required="">
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Sign up</button>
				</form>
			</div>

			<div class="login">
				<form>
					<label for="chk" aria-hidden="true">Login</label>
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Login</button>
				</form>
			</div>
	</div> -->
</body>
</html>
<!-- partial -->
  
</body>
</html>

base_page/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<form class="logout" action="{% url 'base_page:logout' %}" method="post">
    {% csrf_token %}
    
    <div class="topleft"><h1>Welcome to your dashboard {{ request.user.first_name }} {{ request.user.last_name }}!</h1></div>

    <div class="card">
        First Name: <h2>{{ request.user.first_name }}</h2>
        Last Name: <h2>{{ request.user.last_name }}</h2>
        Email <h2> {{ request.user.email }}</h2>
      </div>
        <button class="logout-link">Logout</button>
</form>

{% endblock content %}